# Generated by Django 5.2.8 on 2025-12-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_remove_conversation_participants_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='conversations', to='chats.message'),
        ),
    ]
